### PR TITLE
fix: formatting link

### PR DESCRIPTION
**Pull request by soerenthomsen**
Just some formatting fixes

### CODE REVIEW

**Comment by jbusecke** [comment]
Something weird is going on with the CI, which fails e.g. [here](https://github.com/GliderToolsCommunity/GliderTools/runs/4251179990?check_suite_focus=true). I think this is unrelated, but we need to fix that before merging others.

**Comment by jbusecke** [comment]
Is this still relevant? I would suggest rebasing/merging the newest changes into this branch and seeing if the CI trouble has been fixed.

**Review by jbusecke — APPROVED** [review]

**Comment by callumrollo** [comment]
@MartinMohrmann Has fixed the CI. @soerenthomsen are we good to merge this PR?

**Review by callumrollo — APPROVED** [review]

**Comment by soerenthomsen** [comment]
Thanks a lot @MartinMohrmann and @callumrollo. This was just a mini PR to improve the docs.

**Pull request merged**
