### PR TITLE
fix zenodo doi badge

### PR DESCRIPTION
**Pull request by callumrollo**
@soerenthomsen this links to the original upload on zenodo https://zenodo.org/record/3360280

I'm using the doi to link to it to avoid ambiguity.

There are several other GliderTools uploads though, including this more recent version by Julius https://zenodo.org/record/4815417 

Which should we point to? I can't find any record of the old badge ID on zenodo. It doesn't correspond to any kind of doi

### CODE REVIEW

**Comment by jbusecke** [comment]
There is a way to always point to the most recent version using a separate doi. That is what I would recommend. Let me know if anything is needed from my side.

**Review by MartinMohrmann — CHANGES_REQUESTED** [review]
Hi, I believe you accidentally linked to the [original upload](https://zenodo.org/record/3360280), instead of the link where all the [other, more recent versions](https://zenodo.org/record/4815417) live. Also, your target link is the .svg file itself, while it should point to the repository instead (link should be https://doi.org/10.5281/zenodo.4075238 in my opinion).

**Comment by MartinMohrmann** [comment]
Hm, while the text on the zenodo webpage promises: "_[This DOI](https://doi.org/10.5281/zenodo.4075238) represents all versions, and will always resolve to the latest one_", it does not work for me. I always end up on the 2020.4 version. But at least I get a list of several versions in the right side-bar. Confusing. But please consider the changes from above comment anyway.

**Comment by callumrollo** [comment]
@MartinMohrmann any more changes to be made here, or can we merge?

**Review by MartinMohrmann — APPROVED** [review]

**Pull request merged**
