### PR TITLE
Replace seawater with gsw

### LINKED ISSUE #95: Switch from seawater to gsw
Is there a reason GliderTools still uses the `seawater` toolbox? I believe this is deprecated in favour of `gsw`

There are switch statements in the toolbox functions to use `gsw` if available. The explanation in physics.py appears to be that, unlike `seawater`, `gsw` is not available in Python 2.x. However, glider tools requires Python >= 3.7 so I don't see what value `seawater` adds.

Note: Filipe at condaforge suggests moving from `seawater` to `gsw`  https://github.com/conda-forge/staged-recipes/pull/14282/files/d9f8d646e5a7d7e36ddacd45612382e0837e8b1e#r604367193

This is particularly compelling seeing as he is the maintainer of `seawater` https://pypi.org/project/seawater/

### PR DESCRIPTION
**Pull request by callumrollo**
- [x] Closes #95
 - [x] Tests added

### CODE REVIEW

**Comment by callumrollo** [comment]
The changes to physics were trivial, mostly removing try and except blocks. Now the package will just fail if gsw isn't installed.

In processing the changes were a little trickier. Moving from the seatwater implementation of [O2sat](https://pythonhosted.org/seawater/extras.html?highlight=sato2#seawater.extras.satO2) to the [gsw implementation](https://teos-10.github.io/GSW-Python/gsw_flat.html?highlight=oxygen#gsw.O2sol) changes the input variables and the units of the output. I think I have corrected for this, but it should be reviewed by someone with oxygen processing experience.

This change also adds lat and lon as args to the calc_oxygen function. This will essentially be a breaking change for users

**Comment by jbusecke** [comment]
Hi @callumrollo, thanks for this PR. 

I think there are a couple of things here that we should implement before merging this. 

1) It is tough to review the changes since the formatting is changed for a lot of unrelated code (I assume you are using black to format the code? Let me try to reformat the whole code and implement some CI restrictions for code listing. You would then need to rebase this PR onto the change (happy to help with this). 

2) 
>Now the package will just fail if gsw isn't installed.

We should think if we want to make gsw a strict or optional dependency. Is it needed for every part of the processing? Or could certain modules work without it?

3) Most importantly: 
> n processing the changes were a little trickier. Moving from the seatwater implementation of O2sat to the gsw implementation changes the input variables and the units of the output. I think I have corrected for this, but it should be reviewed by someone with oxygen processing experience.
>
>This change also adds lat and lon as args to the calc_oxygen function. This will essentially be a breaking change for users

Not having test to cover this behavior makes me uneasy to implement such changes. We should at least come up with some synthetic data, capture the output of the current version and see if the new version changes dramatically? If they do and that is expected, that is ok. But implementing this 'blindly' seems dangerous.

**Comment by callumrollo** [comment]
Hi Julius

1. On the formatting, I used the pre-commit hook that currently runs black on the codebase, This was part of the PR template so, if it's not desired behaviour, we should probably change that. The consequential changes are all in the first two commits
2. gsw isn't essential, but I'm not sure how we want to deal with dependencies only needed by some functions. Maybe to be discussed in Issue #98?
3. We could definitely use tests to cover this. One of the original authors would probably be best placed to do it. I can try and throw together some synthetic data, bitI don't have much experience with processing oxygen so not suer how meaningful it would be

**Review by jbusecke — DISMISSED** [review]
I have started the linting in #100, once that is done we can proceed over here.

**Comment by jbusecke** [comment]
I just noticed in #102 that `gsw` is already required form some stuff in `physics.py`, so once that is merged we can work on taking out all references to `seawater`!

**Comment by jbusecke** [comment]
I fixed the merge conflict. I however have one question: In the current implementation `gsw` is a strict dependency. Is the change we want to make? Or should it stay an optional dependency?

**Comment by callumrollo** [comment]
gsw should be a strict dependency imho, as several parts of the toolbox depend on it. This PR removes the seawater dependency.

We should really implement some tests before merging this though. Could use the input of someone with more oxygen processing experience

**Comment by jbusecke** [comment]
Ok sounds good. I agree we should implement tests for the o2 processing first and then continue on this one? Or are you saying we should start from scratch with gsw? 

Perhaps @soerenthomsen has some input (I got no clue about how to actually measure oxygen haha).

**Comment by callumrollo** [comment]
No need to start from scratch, there are only a few functions that use seawater or gsw. It's just that the oxygen function is quite complex and I'm not a domain expert. 

What I could do is write a test to check that the new implementation produces the same oxygen values as the old one.

**Comment by jbusecke** [comment]
> What I could do is write a test to check that the new implementation produces the same oxygen values as the old one.

I think that would be a sufficient solution, which would not require too much drilling into the code, but would at least ensure continuity.

We should clearly note that this should eventually be removed though, because I assume that it would require us to still require `seawater` for testing (but not deployment).

**Comment by callumrollo** [comment]
What I had in mind was to run the old seawater version, write out the resulting oxygen values, then test these values against the new gsw version.

**Comment by soerenthomsen** [comment]
I can try to look into the simple oxygen test next week. It will take a few weeks before we/I can start to write an improved oxygen package as discussed here #74 thus I suggest to keep a simple test for now as you propose @callumrollo.

**Comment by jbusecke** [comment]
> What I had in mind was to run the old seawater version, write out the resulting oxygen values, then test these values against the new gsw version.

Thats actually great. I overcomplicated it.

**Comment by callumrollo** [comment]
This genius plan does, however, depend on a functions calc_oxygen. Gonna pause this for now

**Comment by bastienqueste** [comment]
Give me a week and all my oxygen experience can be yours.

**Comment by soerenthomsen** [comment]
> Give me a week and all my oxygen experience can be yours.

I suggest you let me know when you have time for a quick discussion @bastienqueste how to proceed. And we start from there. As we have now gathered quite a lot of info already in #74 and there is a huge interest in a functioning oxygen module let move this forward!

**Comment by jbusecke** [comment]
Was there any progress on this problem?

**Comment by callumrollo** [comment]
It's tied to the oxygen processing problem in Issue #112. I will try to resolve the oxygen issue with some tests this weekend, then I can progress with sorting this

**Comment by soerenthomsen** [comment]
It will take a few weeks before we really start to refactor the oxygen package. I will not be done before mid/end May. There reason is that right now a best practice document is written on oxygen and I want to have a V1.0 of this document before implementing/refactor etc.

**Comment by callumrollo** [comment]
I'm not sure we can include glider tools in an oxygen best practices when the oxygen processing is broken? It's not a refactor issue. As far as I can tell it's been broken since the package was first published

**Comment by jbusecke** [comment]
> It's tied to the oxygen processing problem in Issue #112. I will try to resolve the oxygen issue with some tests this weekend, then I can progress with sorting this

Thanks for the reminder. If you need anything over there, just ping me.

> I'm not sure we can include glider tools in an oxygen best practices when the oxygen processing is broken? It's not a refactor issue. As far as I can tell it's been broken since the package was first published

Could the best practices be assembled as document and ultimately implemented here?

**Comment by soerenthomsen** [comment]
@callumrollo maybe I was not clear enough. The best practice document will be developed under the umbrella of ocean gliders and after the calibration procedures etc will be implemented here in a new oxygen package. It is not related to the bug but I guess the oxygen package will be totally rewritten.

**Comment by callumrollo** [comment]
Now resolved all the other errors, the only remaining test that fails is that for oxygen. Could be that I've implemented it wrong, could be the old implementation (and therefore test conditions) are wrong

**Review by MartinMohrmann — APPROVED** [review]

**Pull request merged**
