### PR TITLE
fixing issue in brunt_vaisala function that returned None

### LINKED ISSUE #16: Brunt-Vaisalla function not returning anything
**Describe the bug**
When using the function it does not return an array of N2.

**Additional context**
It appears as if the pad_nan function is the issue. When using the GSW function alone it returns a N2 array.

### PR DESCRIPTION
**Pull request by callumrollo**
- [x] Closes #16 
 
Very small fix, sub function `pad_nan` in `brunt_vaisala` did not have a **return** call

### CODE REVIEW

**Review by jbusecke — CHANGES_REQUESTED** [review]
😱 Great catch. Could you add a test that exposes this bug?

**Comment by callumrollo** [comment]
It's currently failing as expected over on #104 does that work?

**Comment by jbusecke** [comment]
Ah I see. I generally think it is easier to do small (atomic) PRs/changes, so I think it is better to add the test here and rebase #104. Alternatively, you could add this fix to #104 but I think there might be more issues that need to be addressed?

**Comment by jbusecke** [comment]
Also thanks a lot for getting into the weeds here! Much appreciated.

**Comment by callumrollo** [comment]
I've added the test for brunt_vaisala to this PR. Is it ok to merge this then fold those changes into #104? That should then pass the CI as the brunt_vaisala test will pass. I haven't rebased before so unsure what I need to do exactly

**Review by jbusecke — APPROVED** [review]
This looks great! I'll merge this now and we can deal with the rebase over at #104

**Pull request merged**
