### PR TITLE
Update CI envs

### PR DESCRIPTION
**Pull request by jbusecke**
- [x] Temporary fix to #136
 - [x] Modernize the CI environment setup
 - [x] Adds  python 3.9 to testing
 - [x] Passes `pre-commit run --all-files`
 - [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

### CODE REVIEW

**Comment by jbusecke** [comment]
So pinning pandas to `<1.3.0` seems to work for now. But we have to find out what is actually causing this problem in [here](https://github.com/GliderToolsCommunity/GliderTools/blame/5db12d687b3b74152c4c351b58826336c0455021/glidertools/load/seaglider.py#L405-L523).

@lukegre do you have any time to look into this?

**Comment by callumrollo** [comment]
Oof. Not something I've looked into before but I can have a go. There's quite a list of depracations in the pandas 1.3.0 changelog, including some on merging dataframes. That would be my first suspicion.

Do we want to merge this now to get the CI improvements? Or get to the bottom of the pandas version issue first?

**Comment by soerenthomsen** [comment]
Thanks a lot @callumrollo. I cannot really answer this but @jbusecke probably. Just tried to help to close this pull-request which seems to be almost done.

**Comment by callumrollo** [comment]
I think I found the source of this. Detail in #136 and fix in #144 

I'd like to review this PR and get it merged, but I don't have write access to this repo

**Comment by soerenthomsen** [comment]
@lukegre could you give @callumrollo write access?

**Comment by soerenthomsen** [comment]
@callumrollo you should be able to merge now! @dhruvbalwada gave you admin rights!

**Review by callumrollo — APPROVED** [review]
Looks good to me

**Comment by callumrollo** [comment]
The docs are failing again. This appears to be due to the changes in `gt.optics.par_dark_count` pushed in the last PR. Weirdly, the docs built on that merge, but now they are failing when it tries to generate docs for that function https://readthedocs.org/projects/glidertools/builds/15237585/

I don't have any experience with readthedocs, but I'll look into a fix

**Comment by callumrollo** [comment]
I'm pretty sure I've resolved the readthedocs issue over in #147 so I'm gonna go ahead and merge this. Thanks @jbusecke!

**Comment by soerenthomsen** [comment]
Thanks @callumrollo ! Appreciate your dedication!

**Pull request merged**
