### PR TITLE
basic physics tests

### PR DESCRIPTION
**Pull request by callumrollo**
- [x] Tests added
Adds a single test for each function in the `physics` module. Uses the netCDFs in tests/data as input and checks that the values returned make physical sense

### CODE REVIEW

**Comment by callumrollo** [comment]
The test for brunt_vaisala will fail until the function is fixed, I'm working on a PR for this now

**Comment by jbusecke** [comment]
Yikes, looks like #100 produced some merge conflicts. These should be relatively easy to mitigate, though. Let me know if you run into problems.

**Comment by jbusecke** [comment]
You can try to fix the conflicts right here in the browser.

When you tap the "resolve conflicts" (or similarly named) button you can edit the file. You will find something like this:
```
>>>>>>>>>>>>>
Code from version a 
--------------
Code from version b that conflicts somehow 
<<<<<<<<<<<<<<
```

Make sure to decide for one of the two and remove all `< - >` symbols. That should do it!

**Comment by callumrollo** [comment]
I've resolved the conflicts, the code style is unhappy though. Not sure how to run pre-commit from within github

**Comment by callumrollo** [comment]
Not the tidiest series of commits, but should pass the code-style check now

**Comment by callumrollo** [comment]
I think we're good to merge @jbusecke

**Comment by jbusecke** [comment]
> Not the tidiest series of commits, but should pass the code-style check now

I'll squash it into one commit anyways, so no worries.

**Review by jbusecke — APPROVED** [review]
Looks good! Thanks for getting the tests started. We will have to extend the tests over time, but this is a great start.

**Pull request merged**
